### PR TITLE
fix: consider microblock transactions in balance calculations

### LINKED ISSUE #2267: new stx balance endpoint returning incorrect amounts in some cases
Reported via Leather: https://github.com/leather-io/extension/issues/6214

Some accounts are reported with incorrect balances. Seems to happen with accounts that have STX locked, such that when the wallet subtracts balance - locked the amount ends up negative.

The current theory is that there could be a re-org bug in the queries introduced in this PR https://github.com/hirosystems/stacks-blockchain-api/pull/2030 but we need to reproduce in a test to confirm.

### PR DESCRIPTION
**Pull request by rafaelcr**
The API has Stacks 2.x logic to avoid re-inserting transactions to the DB during a `/new_block` event when those transactions were previously inserted during a `/new_microblock` event. However, the new /extended/v2 balance endpoint logic only considers `/new_block` transactions when adding/subtracting from account balances. This is causing some old 2.x blocks to warp balances in accounts that happened to have transactions confirmed in previous microblocks.

This PR changes this behavior so these balance calculations always include all transactions regardless of microblocks. It also includes a migration that will execute a query to recompute all transaction balances to correct the issue on deployed environments.

Fixes #2267

### CODE REVIEW

File: migrations/1747151261415_recalculate-balances.js [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+      GROUP BY recipient
+    ),
+    all_addresses AS (
+      SELECT address FROM net_balances
+      UNION
+      SELECT address FROM fees
+      UNION
+      SELECT address FROM rewards
+    )
+    INSERT INTO ft_balances (address, balance, token)
```
Comment (zone117x) [inline migrations/1747151261415_recalculate-balances.js:58]: Does this work with an already populated table? I think the table might need to be dropped first, or this needs something like 
```sql
        ON CONFLICT (address, token)
        DO UPDATE ...
```

Comment (rafaelcr) [reply migrations/1747151261415_recalculate-balances.js:61]: Whoops, forgot that, thanks. Added the TRUNCATE query.

**Review by zone117x — APPROVED** [review]
LGTM!
