### PR TITLE
fix: incorrect websocket/socket.io transaction updates

### LINKED ISSUE #957: return full transaction objects through websockets
The current websocket updates for transactions and balances include very little information about the actual event. For example: An address update only gives users the `tx_id`, `tx_status` and `tx_type`, while socket.io returns a full `AddressTransactionWithTransfers` object with all the details saving one extra API call from the user if they want more info (related: #830)

Since this would be a breaking change for current websocket users (and because #840 is now merged) we should look at metrics for current usage to see the possible impact.

### PR DESCRIPTION
**Pull request by rafaelcr**
This PR fixes issues #1152 and #1153 , but it also refactors our WebSockets pipeline to the following structure:

* Instead of maintaining independent socket.io and ws-rpc controllers (bug prone), `WebSocketTransmitter` was created to receive all blockchain events, query for all relevant data, and finally just relay info to clients via a standardized channel interface
* A `WebSocketChannel` interface was created so we can create as many channels as we need (currently only socket.io and ws-rpc)
* `WsRpcChannel` and `SocketIOChannel` were refactored from the old controllers to manage each channel's subscriptions and relay data from the transmitter to clients

This PR also:
* [x] fixes some mempool events that are not currently transmitted (like garbage collection drops)
* [x] standardizes ws-rpc responses to close #957

### CODE REVIEW

File: src/datastore/pg-write-store.ts [hunk 1]
```diff
@@ -1772,6 +1772,9 @@ export class PgWriteStore extends PgStore {
     `;
     await this.refreshMaterializedView(sql, 'mempool_digest');
     const deletedTxs = deletedTxResults.map(r => r.tx_id);
+    for (const txId of deletedTxs) {
+      await this.notifier?.sendTx({ txId: txId });
```
Comment (zone117x) [inline src/datastore/pg-write-store.ts:1776]: I think this is being called while in a sql transaction from the calling function, right? If so, seems like the deleted txs should be placed in a variable outside of the sql transaction function, then call the notifier after sql tx finishes?

Comment (rafaelcr) [reply src/datastore/pg-write-store.ts:1776]: Good point, done

**Review by zone117x — APPROVED** [review]
Nice abstraction 💯
